language: node_js

node_js:
  - 12.16.3

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  target_branch: master
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: dist
  keep_history: true
  allow_empty_commit: true
  on:
    branch: development
