language: node_js

node_js:
  - stable

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  target_branch: master
  github_token: $GITHUB_TOKEN
  cleanup: true
  keep_history: true
  local_dir: dist
  on:
    branch: development
